using System;
using NXOpen;
using NXOpen.Drawings;

public class NXJournal
{
    public static void Main(string[] args)
    {
        Session theSession = Session.GetSession();
        Part workPart = theSession.Parts.Work;
        Part displayPart = theSession.Parts.Display;
        
        Session.UndoMarkId markId1;
        markId1 = theSession.SetUndoMark(Session.MarkVisibility.Visible, "View Style");
        
        DrawingSheet startSheet = theSession.Parts.Work.DrawingSheets.CurrentDrawingSheet;
        DraftingView[] viewsToSelect = startSheet.GetDraftingViews();
        
        foreach (DraftingView tempView in viewsToSelect)
        {
            tempView.Style.VisibleLines.VisibleColor = 10;
            tempView.Commit();
        }
    }
}
