using NXOpen;
using NXOpen.UF;
using System.Collections.Generic;

public class LayerManagement
{
    public static void Main()
    {
        Session theSession = Session.GetSession();
        Part workPart = theSession.Parts.Work;

        // Xác định Layer 255
        //int targetLayer = 255;

        // Duyệt qua tất cả các đối tượng cần di chuyển
        List<DisplayableObject> objectsToMove = new List<DisplayableObject>();
        objectsToMove.AddRange(workPart.Curves.ToArray());
        objectsToMove.AddRange(workPart.Points.ToArray());
        objectsToMove.AddRange(workPart.Datums.ToArray());
        objectsToMove.AddRange(workPart.Sketches.ToArray());
	   objectsToMove.AddRange(workPart.Lines.ToArray());
        objectsToMove.AddRange(workPart.CoordinateSystems.ToArray());
	  objectsToMove.AddRange(workPart.Splines.ToArray());

        // Chuyển tất cả vào Layer 255
        foreach (DisplayableObject obj in objectsToMove)
        {
            obj.Layer = 255;
        }
NXOpen.Session.UndoMarkId markId = theSession.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Hide Layer 255");

    NXOpen.Layer.StateInfo[] stateArray1 = new NXOpen.Layer.StateInfo[1];
    stateArray1[0] = new NXOpen.Layer.StateInfo(255, NXOpen.Layer.State.Hidden);
    workPart.Layers.ChangeStates(stateArray1, false);


    }
}